openapi: 3.0.0
info:
  title: EasyMarket Server
  version: 0.0.1
components:
  parameters:
    rfid_code:
      name: rfid_code
      in: path
      required: true
      description: Item rfid_code
      schema:
        type: integer
        example: 315748
    qr_code:
      name: qr_code
      in: path
      required: true
      description: Cart qr_code
      schema:
        $ref: "#/components/schemas/qr_code"
  schemas:
    purchase:
      type: integer
      example: 719
    vesttype:
      type: string
      example: "blue"
      enum:
        - blue
    qr_code:
      type: string
      description: Cart qr_code
      example: "5477"
    login:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          maxLength: 100
          example: "josesilva@gmail.com"
        password:
          type: string
          minLength: 5
          maxLength: 100
          example: "senha"
paths:
  /cart/{qr_code}:
    delete: 
      summary: Ending purchase
      operationId: CartEndPurchase
      tags:
        - cart
      parameters:
        - $ref: "#/components/parameters/qr_code"
      responses:
        "200":
          description: "OK"
        "404":
          description: "Cart not found in open purchases"
          
    get:
      summary: maybe get current purchase data for a cart
      operationId: CartCheckOnPurchase
      tags:
        - cart
      parameters:
        - $ref: "#/components/parameters/qr_code"
      responses:
        "404":
          description: "Cart not in current purchase"
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                title: CartStatus
                required:
                  - purchase
                  - VestType
                properties:
                  purchase:
                    $ref: "#/components/schemas/purchase"
                  VestType:
                    $ref: "#/components/schemas/vesttype"

  /item/{rfid_code}:
    get:
      summary: get item data
      operationId: GetItemData
      tags:
        - cart
      parameters:
        - $ref: "#/components/parameters/rfid_code"
      responses:
        "404":
          description: "Item not found"
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                title: ItemData
                required:
                  - name
                  - price
                  - weight
                properties:
                  name:
                    type: string
                  price:
                    type: integer
                    minimum: 0
                  weight:
                    type: integer
                    minimum: 0

            

  /purchase:
    post:
      summary: Start a purchase
      operationId: StartPurchase
      tags:
        - app
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: PurchaseStartReq
              required:
                - login
                - qr_code
                - VestType
              properties:
                login:
                  $ref: "#/components/schemas/login"
                qr_code:
                  $ref: "#/components/schemas/qr_code"
                VestType:
                  $ref: "#/components/schemas/vesttype"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Missing or invalid parameters"
        "403":
          description: "Login failure"
        "409":
          description: "Purchase already in progress"
    get:
      summary: Get current purchase items
      operationId: GetCurrentPurchase
      tags:
        - app
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: LoginReq
              required:
                - login
              properties:
                login:
                  $ref: "#/components/schemas/login"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                title: PurchaseListRes
                items:
                  type: object
                  title: PurchaseItem
                  required:
                    - name
                    - price
                    - amount
                  properties:
                    name:
                      type: string
                      example: "Leite Vaqueiro 1L"
                    price:
                      type: integer
                      minimum: 0
                      example: 299
                    amount:
                      type: integer
                      minimum: 0
                      example: 3

        "403":
          description: "Login failure"
        "404":
          description: "No purchase in progress"       
          
          
    delete:
      summary: End a purchase by the client
      operationId: AppEndPurchase
      tags:
        - app
      description: Tries to end a purchase by either cancelling the purchase (does not include payment) or completing it(includes payment)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: PaymentDataReq
              required:
                - login
              properties:
                login:
                  $ref: "#/components/schemas/login"
                payment:
                  type: integer
                  description: Payment method. Optional (transaction not completed if absent)
                  example: 4748967312
      responses:
        "200":
          description: "OK"
        "402":
          description: "Payment failure"
        "403":
          description: "Login failure"
        "404":
          description: "No purchase in progress"          


          
  /purchase/{purchase_id}/{rfid_code}:
    put:
      summary: alter amount of item in purchase
      operationId: CartAlterItem
      tags:
        - cart
      parameters:
        - $ref: "#/components/parameters/rfid_code"
        - name: purchase_id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/purchase"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: integer
              title: amount
      responses:
        "200":
            description: "OK"
        "404":
            description: "Purchase or item not found"
            
  /client:
    post:
      summary: Add a client
      operationId: NewClient
      tags:
        - app
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: NewLoginReq
              required:
                - name
                - login
              properties:
                login:
                  $ref: "#/components/schemas/login"
                name:
                  type: string
                  maxLength: 100
                  example: "Jose da Silva"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Missing or invalid parameters"
        "409":
          description: "Email already registered"


