openapi: 3.0.0
info:
  title: EasyMarket Server
  version: 0.0.1
components:
  schemas:
    login:
      type: object
      required:
        - email
        - password
      email:
        type: string
        maxLength: 100
        example: "josesilva@gmail.com"
      password:
        type: string
        minLength: 5
        maxLength: 100
        example: "senha"
paths: 
  /client:
    post:
      summary: Add a client
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - login
              properties:
                login:
                  $ref: "#/components/schemas/login"
                name:
                  type: string
                  maxLength: 100
                  example: "Jose da Silva"
      responses:
        "200": 
          description: "OK"
        "400":
          description: "Missing or invalid parameters"
        "409":
          description: "Email already registered"
