BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Comprador" (
	"Nome"	TEXT NOT NULL,
	"Senha"	TEXT NOT NULL,
	"Email"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("Email")
);
CREATE TABLE IF NOT EXISTS "Compra" (
	"Comprador"	INTEGER NOT NULL,
	"Carrinho"	INTEGER NOT NULL,
	"CoresJaqueta"	INTEGER NOT NULL,
	FOREIGN KEY("Comprador") REFERENCES "Comprador"
);
CREATE TABLE IF NOT EXISTS "ItemCompra" (
	"Compra"	INTEGER,
	"Item"	INTEGER,
	"Quantidade"	INTEGER,
	FOREIGN KEY("Compra") REFERENCES "Compra",
	PRIMARY KEY("Item","Compra"),
	FOREIGN KEY("Item") REFERENCES "Item"
);
CREATE TABLE IF NOT EXISTS "Item" (
	"RFIDCode"	INTEGER NOT NULL UNIQUE,
	"Nome"	TEXT NOT NULL,
	"Peso"	INTEGER NOT NULL,
	"Preço"	INTEGER NOT NULL,
	PRIMARY KEY("RFIDCode")
);
COMMIT;
