# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ItemData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, price=None, weight=None):  # noqa: E501
        """ItemData - a model defined in OpenAPI

        :param name: The name of this ItemData.  # noqa: E501
        :type name: str
        :param price: The price of this ItemData.  # noqa: E501
        :type price: int
        :param weight: The weight of this ItemData.  # noqa: E501
        :type weight: int
        """
        self.openapi_types = {
            'name': str,
            'price': int,
            'weight': int
        }

        self.attribute_map = {
            'name': 'name',
            'price': 'price',
            'weight': 'weight'
        }

        self._name = name
        self._price = price
        self._weight = weight

    @classmethod
    def from_dict(cls, dikt) -> 'ItemData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ItemData of this ItemData.  # noqa: E501
        :rtype: ItemData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this ItemData.


        :return: The name of this ItemData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ItemData.


        :param name: The name of this ItemData.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def price(self):
        """Gets the price of this ItemData.


        :return: The price of this ItemData.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this ItemData.


        :param price: The price of this ItemData.
        :type price: int
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501
        if price is not None and price < 0:  # noqa: E501
            raise ValueError("Invalid value for `price`, must be a value greater than or equal to `0`")  # noqa: E501

        self._price = price

    @property
    def weight(self):
        """Gets the weight of this ItemData.


        :return: The weight of this ItemData.
        :rtype: int
        """
        return self._weight

    @weight.setter
    def weight(self, weight):
        """Sets the weight of this ItemData.


        :param weight: The weight of this ItemData.
        :type weight: int
        """
        if weight is None:
            raise ValueError("Invalid value for `weight`, must not be `None`")  # noqa: E501
        if weight is not None and weight < 0:  # noqa: E501
            raise ValueError("Invalid value for `weight`, must be a value greater than or equal to `0`")  # noqa: E501

        self._weight = weight
